// scripts.js

const compliments = {
    eyes: [
        "Your eyes have a way of making the stars jealous.",
        "I could lose myself in your eyes and never want to find my way out.",
        "Your eyes sparkle with a light that is purely magical.",
        "There’s a whole universe in your eyes that I can’t stop exploring.",
        "Your eyes are like deep pools of mystery and wonder.",
        "Whenever I look into your eyes, I see a future full of possibilities.",
        "Your eyes are like twin suns, warming everyone they meet.",
        "I love how your eyes tell a story no words can capture.",
        "Your eyes are the perfect shade of comfort and adventure.",
        "Every glance from you feels like a secret message.",
        "Your eyes are as captivating as a masterpiece painting.",
        "They say the eyes are the windows to the soul, and yours are full of beauty.",
        "The way your eyes light up when you’re happy is my favorite sight.",
        "Your eyes are like rare gems, precious and unique.",
        "I can see the kindness in your eyes, and it makes the world better.",
        "Your eyes are like a tranquil sea, calming and endless.",
        "There’s a fire in your eyes that inspires everyone around you.",
        "Your eyes shine brighter than the moon on the clearest night.",
        "I love the little sparkles in your eyes when you laugh.",
        "Your eyes hold the depth of the ocean and the warmth of the sun.",
        "Looking into your eyes feels like coming home.",
        "Your eyes are like the first morning light, full of promise and hope.",
        "There’s a whole galaxy of love and dreams in your eyes.",
        "Your eyes are the perfect mix of mystery and clarity.",
        "I could stare into your eyes forever and still feel like it’s not enough time.",
        "Your eyes have a gentle strength that calms my heart.",
        "I love how your eyes change color with your mood – it’s fascinating.",
        "Your eyes are like a beautiful sunrise after the longest night.",
        "Your eyes tell me everything I need to know without saying a word.",
        "The way your eyes light up when you’re excited is contagious.",
        "Your eyes are like two bright stars in a dark sky.",
        "There’s a whole story written in your eyes, and it’s my favorite book.",
        "Your eyes have a magical way of making me feel special.",
        "I can see the entire world reflected in your eyes.",
        "Your eyes are the perfect blend of innocence and wisdom.",
        "The way your eyes crinkle when you smile is the cutest thing ever.",
        "Your eyes have a comforting warmth that makes me feel at peace.",
        "I love how your eyes reveal your passion and enthusiasm.",
        "Your eyes are the definition of perfection.",
        "Looking into your eyes is like discovering a hidden treasure.",
        "Your eyes are as refreshing as a cool breeze on a hot day.",
        "Your eyes have a hypnotic quality that’s impossible to resist.",
        "I could get lost in the beauty of your eyes for hours.",
        "Your eyes are like a canvas painted with the colors of joy and love.",
        "Your eyes are the most genuine part of you, and I adore them.",
        "There’s a softness in your eyes that melts my heart.",
        "Your eyes hold a million dreams and a million answers.",
        "Your eyes are like a serene lake, peaceful and inviting.",
        "I love how your eyes reflect your incredible spirit.",
        "Your eyes have a charm that’s all your own.",
        "There’s a depth to your eyes that’s simply mesmerizing.",
        "Your eyes are like a beautiful melody that I can’t get out of my head.",
        "I see the best version of myself in your eyes.",
        "Your eyes are a constant reminder of the beauty in the world.",
        "Your eyes are as enchanting as a fairy tale.",
        "The way your eyes light up when you talk about your passions is inspiring.",
        "Your eyes are like a gentle rain, soothing and refreshing.",
        "There’s a playful sparkle in your eyes that I can’t get enough of.",
        "Your eyes have a calming effect that makes everything feel right.",
        "Your eyes are like a hidden gem, rare and precious.",
        "I love how your eyes always seem to understand me.",
        "Your eyes are like a gentle breeze, refreshing and uplifting.",
        "There’s a sweetness in your eyes that makes me feel loved.",
        "Your eyes have a depth that I could explore forever.",
        "Your eyes are like a beautiful sunset, full of warmth and beauty.",
        "Your eyes are a source of endless fascination for me.",
        "I love how your eyes can convey so much emotion.",
        "Your eyes are like a beautiful poem written in a secret language.",
        "There’s a strength in your eyes that gives me courage.",
        "Your eyes are like a beautiful mystery that I want to unravel.",
        "Your eyes have a magic that’s impossible to describe.",
        "Your eyes are like a beautiful garden, full of life and color.",
        "Your eyes are the perfect mix of elegance and charm.",
        "I love how your eyes reflect your beautiful soul.",
        "Your eyes have a unique sparkle that’s all your own.",
        "Your eyes are like a beautiful dream that I never want to wake up from.",
        "Your eyes are a treasure that I’m lucky to have found.",
        "Your eyes have a comforting light that makes everything better.",
        "Your eyes are like a beautiful painting, full of detail and beauty.",
        "Your eyes have a way of making me feel special and loved.",
        "Your eyes are like a beautiful melody that plays in my heart.",
        "I love how your eyes always seem to see the best in people.",
        "Your eyes are like a beautiful story that I want to read over and over.",
        "Your eyes have a magic that makes the world a better place.",
        "Your eyes are a reflection of your incredible beauty.",
        "Your eyes are like a beautiful symphony that I can’t get enough of.",
        "Your eyes have a warmth that makes me feel at home.",
        "Your eyes are like a beautiful rose, full of beauty and grace.",
        "Your eyes are like a beautiful song that I can’t stop humming.",
        "Your eyes have a depth that’s simply captivating.",
        "Your eyes are like a beautiful river, flowing with grace and beauty.",
        "Your eyes are a constant source of joy and inspiration.",
        "Your eyes are like a beautiful sunrise, full of hope and promise.",
        "Your eyes have a way of making everything feel right.",
        "Your eyes are like a beautiful journey that I never want to end.",
        "Your eyes are a reflection of the incredible person you are.",
        "Your eyes are like a beautiful dream that I never want to leave.",
        "Your eyes have a magic that makes everything better."
    ],
    face: [
        "Your face is like a beautiful work of art, each feature perfectly placed.",
        "You have a face that exudes kindness and warmth.",
        "Your face lights up with joy every time you smile.",
        "Your face is a masterpiece, full of beauty and grace.",
        "You have such an expressive and captivating face.",
        "Your face tells a story of love and kindness.",
        "You have a face that radiates confidence and charm.",
        "Your face is a perfect blend of elegance and beauty.",
        "Your face is as bright and lovely as a spring morning.",
        "You have a face that is both striking and unique.",
        "Your face has a way of making me feel at ease.",
        "You have a face that can brighten the darkest day.",
        "Your face is like a beautiful landscape, full of depth and beauty.",
        "You have a face that is both gentle and strong.",
        "Your face is the perfect canvas of beauty and emotion.",
        "Your face glows with an inner light that is captivating.",
        "You have a face that can launch a thousand dreams.",
        "Your face is so radiant, it could light up a room.",
        "You have a face that is full of charm and grace.",
        "Your face is like a beautiful story, full of intrigue and wonder.",
        "You have a face that is both serene and enchanting.",
        "Your face is a perfect reflection of your beautiful soul.",
        "You have a face that can inspire and uplift.",
        "Your face is so lovely, it takes my breath away.",
        "You have a face that is both strong and delicate.",
        "Your face is a perfect harmony of features and expressions.",
        "You have a face that shines with inner beauty.",
        "Your face is like a beautiful song that I never tire of.",
        "You have a face that is both captivating and unforgettable.",
        "Your face is a perfect blend of classic beauty and modern charm.",
        "You have a face that radiates warmth and love.",
        "Your face is so beautiful, it could stop traffic.",
        "You have a face that is both inviting and mesmerizing.",
        "Your face is a perfect balance of elegance and allure.",
        "You have a face that glows with happiness.",
        "Your face is a perfect expression of your amazing spirit.",
        "You have a face that is full of life and energy.",
        "Your face is so beautiful, it feels like a dream.",
        "You have a face that can calm and soothe.",
        "Your face is a perfect reflection of your inner beauty.",
        "You have a face that is both radiant and serene.",
        "Your face is a perfect blend of charm and sophistication.",
        "You have a face that is full of character and charm.",
        "Your face is so captivating, it’s like a magnet.",
        "You have a face that is both soft and strong.",
        "Your face is a perfect mix of beauty and elegance.",
        "You have a face that shines with kindness.",
        "Your face is so stunning, it’s like a dream come true.",
        "You have a face that is both peaceful and powerful.",
        "Your face is a perfect reflection of your wonderful personality.",
        "You have a face that is full of love and compassion.",
        "Your face is so beautiful, it’s like a poem in motion.",
        "You have a face that is both radiant and inspiring.",
        "Your face is a perfect blend of grace and strength.",
        "You have a face that lights up the room.",
        "Your face is so mesmerizing, it’s hard to look away.",
        "You have a face that is full of beauty and wonder.",
        "Your face is a perfect expression of joy and happiness.",
        "You have a face that is both beautiful and unforgettable.",
        "Your face is so lovely, it makes my heart skip a beat.",
        "You have a face that is full of life and vitality.",
        "Your face is a perfect blend of serenity and energy.",
        "You have a face that is both enchanting and inviting.",
        "Your face is so beautiful, it feels like magic.",
        "You have a face that is full of love and light.",
        "Your face is a perfect reflection of your incredible spirit.",
        "You have a face that is both radiant and kind.",
        "Your face is so stunning, it’s like a work of art.",
        "You have a face that is full of warmth and compassion.",
        "Your face is a perfect mix of elegance and charm.",
        "You have a face that is both captivating and serene.",
        "Your face is so beautiful, it’s like a fairytale.",
        "You have a face that is full of grace and beauty.",
        "Your face is a perfect expression of love and joy.",
        "You have a face that is both strong and gentle.",
        "Your face is so lovely, it’s like a melody.",
        "You have a face that is full of hope and optimism.",
        "Your face is a perfect blend of beauty and brilliance.",
        "You have a face that is both radiant and elegant.",
        "Your face is so mesmerizing, it’s like a dream.",
        "You have a face that is full of kindness and warmth.",
        "Your face is a perfect reflection of your beautiful heart.",
        "You have a face that is both captivating and radiant.",
        "Your face is so stunning, it’s like a vision.",
        "You have a face that is full of life and love.",
        "Your face is a perfect blend of serenity and strength.",
        "You have a face that is both enchanting and unique.",
        "Your face is so beautiful, it’s like a masterpiece.",
        "You have a face that is full of joy and happiness.",
        "Your face is a perfect expression of your inner beauty.",
        "You have a face that is both radiant and inviting.",
        "Your face is so lovely, it’s like a beautiful dream.",
        "You have a face that is full of light and love."
    ],
    body: [
        "Your body is a testament to your strength and resilience.",
        "You have an amazing figure that perfectly complements your personality.",
        "Your body is a work of art, sculpted with care and love.",
        "You have a body that exudes confidence and grace.",
        "Your body is perfect just the way it is, a beautiful reflection of who you are.",
        "You have a body that radiates vitality and energy.",
        "Your body is a wonderful canvas of beauty and strength.",
        "You have a body that is both powerful and elegant.",
        "Your body is a perfect blend of athleticism and grace.",
        "You have a body that is full of life and vitality.",
        "Your body is a perfect example of balance and harmony.",
        "You have a body that is both strong and agile.",
        "You have a body that moves with elegance and poise.",
        "Your body is a testament to your hard work and dedication.",
        "You have a body that is both flexible and strong.",
        "Your body is a perfect harmony of strength and grace.",
        "You have a body that is full of stamina and endurance.",
        "Your body is a wonderful blend of power and beauty.",
        "You have a body that is both resilient and graceful.",
        "Your body is a testament to your inner strength and determination.",
        "You have a body that is both athletic and elegant.",
        "Your body is a wonderful reflection of your vibrant spirit.",
        "You have a body that is both toned and graceful.",
        "Your body is a perfect example of balance and proportion.",
        "You have a body that is full of strength and energy.",
        "Your body is a wonderful display of resilience and power.",
        "You have a body that moves with beauty and grace.",
        "Your body is a testament to your incredible spirit and strength.",
        "You have a body that is both agile and powerful.",
        "Your body is a perfect harmony of beauty and strength.",
        "You have a body that is full of endurance and vitality.",
        "Your body is a wonderful blend of flexibility and power.",
        "You have a body that is both strong and elegant.",
        "Your body is a testament to your inner beauty and strength.",
        "You have a body that is full of life and energy.",
        "Your body is a perfect reflection of your amazing personality.",
        "You have a body that is both powerful and graceful.",
        "Your body is a wonderful display of beauty and resilience.",
        "You have a body that is both athletic and graceful.",
        "Your body is a testament to your incredible determination.",
        "You have a body that is full of strength and vitality.",
        "Your body is a wonderful blend of power and elegance.",
        "You have a body that is both flexible and strong.",
        "Your body is a perfect example of beauty and strength.",
        "You have a body that is full of stamina and resilience.",
        "Your body is a wonderful display of health and beauty.",
        "You have a body that moves with elegance and power.",
        "Your body is a testament to your hard work and dedication.",
        "You have a body that is both toned and flexible.",
        "Your body is a perfect harmony of strength and beauty.",
        "You have a body that is full of endurance and energy.",
        "You have a body that is both powerful and resilient.",
        "Your body is a testament to your incredible spirit and strength.",
        "You have a body that is full of life and vitality.",
        "Your body is a wonderful reflection of your inner beauty.",
        "You have a body that is both agile and powerful.",
        "Your body is a perfect example of balance and grace.",
        "You have a body that is full of strength and energy.",
        "Your body is a wonderful display of flexibility and power.",
        "You have a body that moves with beauty and grace.",
        "Your body is a testament to your inner strength and determination.",
        "You have a body that is both athletic and elegant.",
        "Your body is a perfect reflection of your vibrant spirit.",
        "Your body is a wonderful blend of power and beauty.",
        "You have a body that is both strong and graceful.",
        "Your body is a testament to your incredible spirit and strength.",
        "You have a body that is full of endurance and energy.",
        "Your body is a wonderful display of beauty and power.",
        "You have a body that moves with elegance and poise.",
        "Your body is a perfect harmony of strength and beauty.",
        "You have a body that is both flexible and powerful.",
        "Your body is a testament to your hard work and dedication.",
        "You have a body that is full of life and vitality.",
        "You have a body that is both powerful and resilient.",
        "Your body is a perfect reflection of your inner beauty.",
        "You have a body that is full of strength and energy.",
        "Your body is a wonderful display of flexibility and elegance.",
        "You have a body that moves with beauty and power.",
        "Your body is a testament to your incredible determination.",
        "Your body is a perfect example of balance and strength.",
        "You have a body that is full of endurance and resilience.",
        "Your body is a wonderful blend of power and beauty.",
        "Your body is a testament to your vibrant spirit and strength.",
        "You have a body that is full of life and energy.",
        "Your body is a wonderful reflection of your incredible spirit.",
        "You have a body that is both strong and elegant.",
        "Your body is a masterpiece, sculpted with grace and elegance.",
"You possess a beauty that emanates from within, reflecting in every contour of your body.",
"Your body is a canvas of beauty, each curve and line telling a story of resilience and grace.",
"Your presence is like poetry in motion, each movement a testament to your inner strength and beauty.",
"Your body is a reflection of the strength and beauty within, a true work of art.",
"Every inch of your body exudes beauty and confidence, a true embodiment of grace.",
"Your body is a symphony of beauty, each part harmonizing to create a masterpiece.",
"Your essence radiates through your body, illuminating the world with your unique beauty.",
"Your body is a sanctuary of beauty and strength, a testament to your inner and outer resilience.",
"Your beauty transcends physicality, touching hearts and souls with every glance.",
"Your body is a celebration of life, a reflection of your vibrant spirit and boundless energy.",
"Your presence is captivating, your body a beacon of beauty and strength.",
"Your body is a treasure trove of beauty, each curve a testament to your strength and grace.",
"Your beauty is timeless, your body a testament to the enduring power of grace.",
"Your essence shines through your body, lighting up the world with your radiant beauty.",
"Your body is a reflection of your inner light, shining brightly for all to see.",
"Your presence commands attention, your body a testament to your confidence and beauty.",
"Your beauty is unmatched, your body a masterpiece of elegance and strength.",
"Your body is a sanctuary of beauty, a testament to your unwavering confidence and grace.",
"Your presence is magnetic, your body a canvas of beauty and strength."

        
        
    ],
    smile: [
        "Your smile is like a ray of sunshine, brightening even the darkest days.",
        "Your smile has the power to lift spirits and warm hearts.",
        "Your smile is as radiant as a thousand suns.",
        "Your smile is the most beautiful thing I’ve ever seen.",
        "Your smile lights up the room like no other.",
        "Your smile has a way of making everything better.",
        "Your smile is like a beacon of joy and happiness.",
        "Your smile is simply contagious.",
        "Your smile is the highlight of my day.",
        "Your smile could melt the coldest of hearts.",
        "Your smile has a magical way of making everything right.",
        "Your smile is the epitome of beauty and grace.",
        "Your smile is as bright and beautiful as a summer morning.",
        "Your smile has the power to chase away all worries.",
        "Your smile is a reflection of your inner beauty.",
        "Your smile is like a beautiful melody that I never tire of.",
        "Your smile is so enchanting, it’s hard to look away.",
        "Your smile is the perfect expression of happiness.",
        "Your smile has a warmth that is simply irresistible.",
        "Your smile is like a beautiful sunrise, full of promise and hope.",
        "Your smile is as charming as it is beautiful.",
        "Your smile has a way of making the world a better place.",
        "Your smile is the most wonderful thing in the world.",
        "Your smile has a way of making me feel special.",
        "Your smile is like a beautiful work of art, perfect in every way.",
        "Your smile is as sweet as it is beautiful.",
        "Your smile has a way of lighting up my heart.",
        "Your smile is a source of endless joy and inspiration.",
        "Your smile is the perfect reflection of your amazing personality.",
        "Your smile is like a gentle breeze, refreshing and uplifting.",
        "Your smile has a charm that is all your own.",
        "Your smile is as bright and lovely as a starry night.",
        "Your smile is the most beautiful thing I’ve ever seen.",
        "Your smile has a way of making everything better.",
        "Your smile is like a beautiful flower, full of life and beauty.",
        "Your smile is as radiant as the sun.",
        "Your smile has a warmth that can brighten anyone’s day.",
        "Your smile is like a beautiful melody that I can’t get out of my head.",
        "Your smile is the perfect expression of joy and happiness.",
        "Your smile has a magic that is simply captivating.",
        "Your smile is as lovely as a blooming rose.",
        "Your smile is the most precious thing in the world.",
        "Your smile has a way of making the world a brighter place.",
        "Your smile is like a beautiful dream that I never want to wake up from.",
        "Your smile is as enchanting as a fairy tale.",
        "Your smile has a way of making me feel at home.",
        "Your smile is the perfect blend of beauty and grace.",
        "Your smile is like a beautiful song that I never tire of hearing.",
        "Your smile has a magic that is simply irresistible.",
        "Your smile is as beautiful as a work of art.",
        "Your smile is the most wonderful thing in the world.",
        "Your smile has a way of making everything feel right.",
        "Your smile is like a gentle rain, refreshing and calming.",
        "Your smile is as bright and lovely as a sunny day.",
        "Your smile has a warmth that can melt the coldest of hearts.",
        "Your smile is like a beautiful sunset, full of warmth and beauty.",
        "Your smile is the most precious gift I’ve ever received.",
        "Your smile has a way of making the world a better place.",
        "Your smile is like a beautiful dream that I never want to end.",
        "Your smile is as charming as it is beautiful.",
        "Your smile has a magic that is simply captivating.",
        "Your smile is like a beautiful flower, full of life and beauty.",
        "Your smile is the most wonderful thing in the world.",
        "Your smile has a way of making everything better.",
        "Your smile is like a gentle breeze, refreshing and uplifting.",
        "Your smile is as bright and lovely as a starry night.",
        "Your smile has a warmth that can brighten anyone’s day.",
        "Your smile is like a beautiful melody that I can’t get out of my head.",
        "Your smile is the perfect expression of joy and happiness.",
        "Your smile has a magic that is simply irresistible.",
        "Your smile is as lovely as a blooming rose.",
        "Your smile is the most precious thing in the world.",
        "Your smile has a way of making the world a brighter place.",
        "Your smile is like a beautiful dream that I never want to wake up from.",
        "Your smile is as enchanting as a fairy tale.",
        "Your smile has a way of making me feel at home.",
        "Your smile is the perfect blend of beauty and grace.",
        "Your smile is like a beautiful song that I never tire of hearing.",
        "Your smile has a magic that is simply captivating.",
        "Your smile is as beautiful as a work of art.",
        "Your smile is the most wonderful thing in the world.",
        "Your smile has a way of making everything feel right.",
        "Your smile is like a gentle rain, refreshing and calming.",
        "Your smile is as bright and lovely as a sunny day.",
        "Your smile has a warmth that can melt the coldest of hearts.",
        "Your smile is like a beautiful sunset, full of warmth and beauty.",
        "Your smile is the most precious gift I’ve ever received.",
        "Your smile has a way of making the world a better place.",
        "Your smile is like a beautiful dream that I never want to end."
    ]
};


function generateCompliment(type) {
    const complimentList = compliments[type];
    const randomIndex = Math.floor(Math.random() * complimentList.length);
    const randomCompliment = complimentList[randomIndex];
    document.getElementById('compliment').textContent = randomCompliment;
}
